# Generated by Django 3.1 on 2020-12-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMadeEasy', '0002_auto_20201204_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='int_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='loan',
            name='outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
