# Generated by Django 3.1 on 2020-12-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMadeEasy', '0003_auto_20201204_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='savings_goal',
            new_name='goal_savings',
        ),
    ]
