# Generated by Django 3.1 on 2020-12-05 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMadeEasy', '0004_auto_20201204_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('int_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='simpleexpense',
            name='belongs_to',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='expenses',
            new_name='total_expenses',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='SimpleExpense',
        ),
        migrations.AddField(
            model_name='expense',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
