# Generated by Django 3.1 on 2020-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMadeEasy', '0005_auto_20201205_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='term',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
