# Generated by Django 3.1 on 2020-12-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMadeEasy', '0006_expense_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='term',
            new_name='term_len',
        ),
    ]
